# Generated by Django 3.0 on 2019-12-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('Noise Complaints', 'Noise'), ('Water Issues', 'Water System'), ('Electrical Problems', 'Electrical'), ('Rodent Infestation', 'Rodent'), ('Hazards', 'Hazardous Materials'), ('Asbestos on Site', 'Asbestos')], max_length=255)),
            ],
        ),
    ]
